name: Deploy to GH Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tags: [latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Build zack website
        run: |
          npm install
          npm run build
        env:
          CI: ""
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
